# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca3c1633a45dca39fa5cc0f49b1183a7b80ddee013dfa135c0baac350e4e0f03fc1902fddc16d0341db837486fd0a67c5858844149c905591d979870e51a3909

test:
  secret_key_base: 90ae263d3d8dbb79c2c8c009c573c6d9bdbf83f47e5120d54448ddbcfd556c45d54cebdfaf48f1daf8492e74bb034d104d93f7c57a3cadc4912b08fc173e5d6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
